version: 3
endpoint: '{{ HASURA_GRAPHQL_ENDPOINT_BASE }}'
admin_secret: '{{ HASURA_GRAPHQL_ADMIN_SECRET }}'
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: '{{ ACTIONS_BASE_URL }}'
